<?php
/**
 * build_reference.php — maintenance script (manual run) for AI Question Authoring.
 *
 * Produces the two committed build artifacts the generation pipeline relies on:
 *   includes/ai/authoring-reference.md   — cleaned "Writing Questions" section of
 *                                          help.html (the always-cached core ref)
 *   includes/ai/library-manifest.json    — one {name, summary} per macro library
 *                                          (the router's menu)
 *
 * Re-run by hand whenever help.html or assessment/libs/*.html change:
 *   docker compose exec app php includes/ai/build_reference.php
 *   (or:  php includes/ai/build_reference.php  from the web root)
 *
 * CLI only — it writes files into the repo and needs no web context.
 */

if (PHP_SAPI !== 'cli') {
    http_response_code(403);
    echo "build_reference.php must be run from the command line.\n";
    exit(1);
}

require_once __DIR__ . '/../aiquestion_libs.php';

$base    = aiLibsBaseDir();                 // web root
$helpFile = $base . '/help.html';
$outRef  = __DIR__ . '/authoring-reference.md';
$outMan  = __DIR__ . '/library-manifest.json';

$exit = 0;

/* ---- 1. Slice + clean the Writing Questions section --------------------- */
echo "Building authoring-reference.md ...\n";
if (!is_readable($helpFile)) {
    fwrite(STDERR, "ERROR: cannot read $helpFile\n");
    exit(1);
}
$lines = file($helpFile, FILE_IGNORE_NEW_LINES);
$start = null;
$end   = count($lines);
foreach ($lines as $i => $line) {
    if ($start === null) {
        if (preg_match('/<h1\s+id="writingquestions"/i', $line)) {
            $start = $i;
        }
    } else {
        // Stop at the next top-level <h1 ...> (e.g. id="usingimas").
        if (preg_match('/<h1\s+id="/i', $line)) {
            $end = $i;
            break;
        }
    }
}
if ($start === null) {
    fwrite(STDERR, "ERROR: could not find <h1 id=\"writingquestions\"> in help.html\n");
    exit(1);
}
$sectionHtml = implode("\n", array_slice($lines, $start, $end - $start));
$refText = aiCleanHelpHtml($sectionHtml);

$header = "# IMathAS Question Authoring Reference\n" .
          "# (auto-generated by includes/ai/build_reference.php from help.html — do not edit by hand)\n\n";
if (file_put_contents($outRef, $header . $refText . "\n") === false) {
    fwrite(STDERR, "ERROR: could not write $outRef\n");
    $exit = 1;
} else {
    $tok = (int)round(strlen($refText) / 4);
    printf("  wrote %s (%d bytes, ~%dk tokens, lines %d-%d of help.html)\n",
        basename($outRef), strlen($refText), (int)round($tok / 1000), $start + 1, $end);
}

/* ---- 2. Build the library manifest ------------------------------------- */
echo "Building library-manifest.json ...\n";
$libs = aiKnownLibraries();
$manifest = array();
foreach ($libs as $name) {
    $manifest[] = array(
        'name'    => $name,
        'summary' => aiLibrarySummary($name),
    );
}
$json = json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
if (file_put_contents($outMan, $json . "\n") === false) {
    fwrite(STDERR, "ERROR: could not write $outMan\n");
    $exit = 1;
} else {
    $tok = (int)round(strlen($json) / 4);
    printf("  wrote %s (%d libraries, %d bytes, ~%d tokens)\n",
        basename($outMan), count($manifest), strlen($json), $tok);
}

echo $exit === 0 ? "Done.\n" : "Completed with errors.\n";
exit($exit);
